### ISSUE TITLE
[PE-D] list unflag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-2/tp#210]
This gives a response "Listed all clients" even thought I only search for "list unplug"

![image.png](https://raw.githubusercontent.com/Geralddtan/ped/main/files/3ea2af43-be45-436e-91cc-15bfc724fd76.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Geralddtan/ped#10

**Comment by Vishwanth2210** [comment]
Hi! Thank you for bringing this up. We would like to point out that a `flag` client has a red bar on the left of the contact details. Since there is no red bar on the left, this `list unflag` command is working as intended. If this is not the issue you pointed out, please feel free to provide more details regarding the issue faced as we would try out best to solve it.
